### ISSUE TITLE
use unittest.mock instead of mock when mock is not available

### ISSUE THREAD

**Issue by pgajdos** [cjw296/coveralls-check#3]
Could you please consider use unittest.mock instead of mock?

**Comment by pgajdos** [comment]
For example:
https://build.opensuse.org/package/view_file/home:pgajdos:python/python-coveralls-check/python-coveralls-check-no-mock.patch

**Comment by cjw296** [comment]
Mock is a rolling backport of unittest.mock, it's not obsolete; I know, I'm its maintainer.

**Comment by pgajdos** [comment]
@cjw296, makes sense, sorry. Would it be possible to fallback to unittest.mock when mock is not installed?
